add_rules("mode.debug", "mode.release")

task("amalgamate")
    on_run(function()
        -- 获取 Commit Short Hash
        local commit_hash = "unknown"
        local hash_result = os.iorun("git rev-parse --short HEAD")
        if hash_result and hash_result:find("fatal:") == nil then
            commit_hash = hash_result:gsub("%s+", "")
        end

        -- 生成时间戳
        local timestamp = os.date("%Y-%m-%d %H:%M:%S")

        -- 运行合并命令
        os.exec("xmake l cli.amalgamate -o .")

        -- 读取生成的内容
        local content = io.readfile("generator.h")

        -- 注入版本信息
        local header = string.format([[
// ==================================================
// Auto-generated by xmake amalgamate
// Commit: %s
// Timestamp: %s
// ==================================================

]], commit_hash, timestamp)

        -- 重新写入文件
        io.writefile("generator.h", header .. content)
    end)
    set_menu {
        description = "合并头文件并注入版本信息"
    }

target("generator")
    set_kind("headeronly")
    add_includedirs("src") 
    add_headerfiles("src/basic/*.h")
    add_headerfiles("src/io/*.h")
    add_headerfiles("src/log/*.h")
    add_headerfiles("src/rand/*.h")
    add_headerfiles("src/graph/*.h")
    add_headerfiles("src/include_all.h")
